Vagrant.configure("2") do |config|
  
  config.vm.box = "docker-ec2"

  config.vm.provider :aws do |aws, override|
    # aws.ami = "ami-cfbcdea6"
    # aws.region = "us-east-1"

    aws.access_key_id = "YOUR_ACCESS_KEY_ID"
    aws.secret_access_key = "YOUR_SECRET_ACCESS_KEY"
    aws.keypair_name = "YOUR_KEYPAIR_NAME"
    aws.security_groups = "YOUR_SECURITY_GROUP"


    override.ssh.private_key_path = "PATH_TO_YOUR_PRIVATE_KEY"
  end
end