Vagrant.configure("2") do |config|
  
  config.vm.box = "docker-ec2"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-cfbcdea6"
    aws.region = "us-east-1"

    override.ssh.username = "ubuntu"
  end
end